name: push the code to the s3 bucket
on:
  push:
    branches:
      - main
jobs:
  deploy-on-s3:
    runs-on: ubuntu-latest

    steps:
      - name: check out the repo
        uses: actions/checkout@v2

      - name: install node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: install the dependencies
        run: npm install

      - name: build the code
        run: npm run build

      - name: login to the aws
        uses: aws-actions/configure-aws-credentials@v1
        with: 
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: 'eu-north-1'

      - name: push to the s3 bucket
        run: |
          aws s3 sync ./build s3://alokranjan-portfolio --delete

